//484
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("2.19.484.0314")]
[assembly: AssemblyFileVersion("2.19.484.0314")]
[assembly: AssemblyCopyright("Copyright © 2012 - 2018")]



